name: Vitta API CI
on:
  push:
    branches:    
      - master
    paths:
      - api/**
      - .github/workflows/api.yaml
  pull_request:
    branches:
      - master
    paths:
      - api/**
      - .github/workflows/api.yaml
  release:
    types: [published]
jobs:
  ci:
    name: Integration Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23'
      - name: Go Version
        run: go version
      - name: Run Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          working-directory: api
      - name: Run Build
        run: make build
      - name: Run Test & Cover
        run: make cover
